### ISSUE TITLE
Add docker registry

### ISSUE THREAD

**Issue by FatmanUK** [FatmanUK/k3s_playground#28]
https://www.tomas.io/articles/docker-registry

Docker registry works with containerd, right?

**Comment by FatmanUK** [comment]
Seems like this is needed. Docker Hub is limited.

**Comment by athajaerel** [comment]
https://docs.docker.com/docker-hub/mirror/

**Comment by FatmanUK** [comment]
https://thomasdegraaff.eu/notes/2021/12/04/k3s_docker_pull_through_registry

**Comment by FatmanUK** [comment]
https://bryanbende.com/development/2021/05/15/k3s-raspberry-pi-volumes-storage

**Comment by FatmanUK** [comment]
https://rpi4cluster.com/k3s/k3s-storage-setting/
