### ISSUE TITLE
New manifests

### ISSUE THREAD

**Issue by FatmanUK** [FatmanUK/k3s_playground#66]
Based on: https://medium.com/picus-security-engineering/creating-air-gapped-k3s-system-images-with-private-registry-a81dd7116331

New manifests.

1. Get base images.
https://github.com/k3s-io/k3s/blob/v1.28.4+k3s2/scripts/airgap/image-list.txt

images=$(cat "${airgap_image_file}")
xargs -n1 docker pull <<< "${images}"
docker save ${images} -o dist/artifacts/k3s-airgap-images-${ARCH}.tar
upload to /var/lib/rancher/k3s/agent/images/ , thenceforth available in containerd.

eg.
$ docker pull longhornio/longhorn-engine:v1.5.3
$ docker pull longhornio/longhorn-instance-manager:v1.5.3
$ docker save longhornio/longhorn-engine:v1.5.3 longhornio/longhorn-instance-manager:v1.5.3 -o longhorn_images.tar
$ ssh k3s-mother-001 sudo mkdir -p /var/lib/rancher/k3s/agent/images
$ tar cpzf - longhorn-*tar | ssh k3s-mother-001 sudo tar xvpzf - -C /var/lib/rancher/k3s/agent/images/

2. Set containerd to never pull from docker.io.

3. Something else useful in that article?

**Comment by athajaerel** [comment]
Something is messed up with ingress-nginx versions.

**Comment by athajaerel** [comment]
Is it nginx-ingress or ingress-nginx? I've seen both.
